pool:
  name: Hosted VS2017
  demands: npm

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: src
      verbose: false

  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: custom
      workingDir: src
      verbose: false
      customCommand: 'run build'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      arguments: '-c Release'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      projects: 'tests/**/*.csproj'
